services:
  # WB API сервис
  wb-api:
    build:
      context: ./monorepo-root/wb-api
      dockerfile: Dockerfile
    container_name: wb-api
    ports:
      - "3006:3006"  # HTTP health endpoint
      - "3000:3000"  # gRPC server
    environment:
      - NODE_ENV=production
      - PORT=3006
      - GRPC_PORT=3000
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - wb-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  wb-network:
    driver: bridge 