version: '3.8'

services:
  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: product-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - product-network

  # gRPC микросервис фильтрации продуктов
  product-filter-service:
    build:
      context: ./monorepo-root/product-filter-service
      dockerfile: Dockerfile
    container_name: product-filter-service
    ports:
      - "3001:3001"
      - "50051:50051"
    environment:
      - REDIS_URL=redis://redis:6379
      - GRPC_PORT=50051
      - GRPC_HOST=0.0.0.0
      - PORT=3001
      - LOG_LEVEL=info
    depends_on:
      - redis
    volumes:
      - ./product-filter-service/logs:/app/logs
    networks:
      - product-network
    restart: unless-stopped

  # WB API сервис
  wb-api:
    build:
      context: ./monorepo-root/wb-api
      dockerfile: Dockerfile
    container_name: wb-api
    ports:
      - "3006:3006"  # HTTP health endpoint
      - "3000:3000"  # gRPC server
    environment:
      - NODE_ENV=production
      - PORT=3006
      - GRPC_PORT=3000
      - REDIS_URL=redis://redis:6379
      - PRODUCT_FILTER_SERVICE_URL=product-filter-service:50051
      - LOG_LEVEL=info
    depends_on:
      - redis
      - product-filter-service
    networks:
      - product-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DB API сервис (гибридный REST + gRPC)
  db-api:
    build:
      context: ./monorepo-root/db-api
      dockerfile: Dockerfile
    container_name: db-api
    ports:
      - "3003:3003"
      - "50052:50051"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/marketvision
      - GRPC_URL=0.0.0.0:50051
      - PORT=3003
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - product-network
    restart: unless-stopped

  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=marketvision
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product-network
    restart: unless-stopped

  # Ozon API сервис (Python)
  ozon-api:
    build:
      context: ./monorepo-root/ozon-api
      dockerfile: Dockerfile
    container_name: ozon-api
    ports:
      - "3002:3002"  # gRPC сервер
      - "3005:3005"  # HTTP health endpoint
    environment:
      - REDIS_URL=redis://redis:6379
      - PRODUCT_FILTER_SERVICE_URL=product-filter-service:50051
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    depends_on:
      - redis
    networks:
      - product-network
    restart: unless-stopped

  # DNS API сервис (Python)
  dns-api:
    build:
      context: ./monorepo-root/dns-api
      dockerfile: Dockerfile
    container_name: dns-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PRODUCT_FILTER_SERVICE_URL=product-filter-service:50051
    depends_on:
      - redis
      - product-filter-service
    networks:
      - product-network
    restart: unless-stopped

  # MarketVision API (Next.js фронтенд)
  marketvision-api:
    build:
      context: ./monorepo-root/marketvision-api
      dockerfile: Dockerfile
    container_name: marketvision-api
    ports:
      - "3004:3004"  # Веб-интерфейс согласно Developer Guide
    environment:
      - NODE_ENV=production
      - PORT=3004
      - NEXT_PUBLIC_API_URL=http://localhost:3003/api
      - PRODUCT_FILTER_SERVICE_URL=http://product-filter-service:3001
    depends_on:
      - db-api
      - product-filter-service
    networks:
      - product-network
    restart: unless-stopped

  # Telegram Bot
  telegram-bot:
    build:
      context: ./monorepo-root/bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    environment:
      - NODE_ENV=production
      - WB_API_URL=http://wb-api:3000
      - DNS_API_URL=http://dns-api:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - wb-api
      - dns-api
    networks:
      - product-network
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:

networks:
  product-network:
    driver: bridge 