services:
  # Telegram Bot
  telegram-bot:
    build:
      context: ./monorepo-root/bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    environment:
      - NODE_ENV=production
      - WB_API_URL=http://wb-api:3000
      - DNS_API_URL=http://dns-api:8000
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 