version: '3.8'

services:
  # Frontend (Next.js)
  marketvision-frontend:
    build: ./monorepo-root/marketvision-api
    container_name: marketvision-frontend
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
    volumes:
      - ./monorepo-root/marketvision-api/logs:/usr/src/app/logs
    restart: unless-stopped
    networks:
      - marketvision-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database API
  marketvision-database-api:
    build: ./monorepo-root/db-api
    container_name: marketvision-database-api
    ports:
      - "3004:3004"  # REST API
      - "50051:50051"  # gRPC
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://marketvision:password@postgres:5432/marketvision
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - marketvision-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Product Filter Service
  marketvision-product-aggregator:
    build: ./monorepo-root/product-filter-service
    container_name: marketvision-product-aggregator
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - WB_API_URL=marketvision-wb-parser:3000
      - OZON_API_URL=marketvision-ozon-parser:3002
      - DB_API_URL=marketvision-database-api:50051
      - GRPC_USE_SSL=false
      - OZON_API_TOKEN=marketvision_secret_token_2024
      - WB_API_TOKEN=marketvision_secret_token_2024
      - DB_API_TOKEN=marketvision_secret_token_2024
      - PORT=3001
      - LOG_LEVEL=info
    volumes:
      - ./monorepo-root/product-filter-service/logs:/usr/src/app/logs
    depends_on:
      - marketvision-database-api
      - marketvision-wb-parser
      - marketvision-ozon-parser
    restart: unless-stopped
    networks:
      - marketvision-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # WB Parser
  marketvision-wb-parser:
    build: ./monorepo-root/wb-api
    container_name: marketvision-wb-parser
    ports:
      - "3000:3000"  # gRPC
      - "3003:3003"  # HTTP health check
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - marketvision-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ozon Parser
  marketvision-ozon-parser:
    build: ./monorepo-root/ozon-api
    container_name: marketvision-ozon-parser
    ports:
      - "3002:3002"  # gRPC
      - "3005:3005"  # HTTP health check
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
      - OZON_API_TOKEN=${OZON_API_TOKEN}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    shm_size: '2gb'
    restart: unless-stopped
    networks:
      - marketvision-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: marketvision-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: marketvision
      POSTGRES_USER: marketvision
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - marketvision-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketvision"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: marketvision-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./monorepo-root/tls:/etc/nginx/certs:ro
    depends_on:
      - marketvision-frontend
      - marketvision-database-api
      - marketvision-product-aggregator
    restart: unless-stopped
    networks:
      - marketvision-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Telegram Bot
  marketvision-telegram-bot:
    build: 
      context: ./monorepo-root/bot
      target: production
    container_name: marketvision-telegram-bot
    environment:
      - NODE_ENV=production
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    depends_on:
      - marketvision-database-api
      - marketvision-product-aggregator
    restart: unless-stopped
    networks:
      - marketvision-net
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  marketvision-net:
    driver: bridge
