services:
  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: product-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - product-filter-network

  # gRPC микросервис фильтрации продуктов
  product-filter-service:
    build:
      context: ./monorepo-root/product-filter-service
      dockerfile: Dockerfile
    container_name: product-filter-service
    ports:
      - "3001:3001"  # HTTP API
      - "50051:50051"  # gRPC
    environment:
      - REDIS_URL=redis://redis:6379
      - GRPC_PORT=50051
      - GRPC_HOST=0.0.0.0
      - PORT=3001
      - LOG_LEVEL=info
    depends_on:
      - redis
    volumes:
      - ./product-filter-service/logs:/app/logs
    restart: unless-stopped
    networks:
      - product-filter-network

volumes:
  redis_data:

networks:
  product-filter-network:
    driver: bridge 