version: '3.8'

services:
  marketvision-api:
    build: .
    container_name: marketvision-frontend
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./next.config.ts:/usr/src/app/next.config.ts
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - marketvision-net

networks:
  marketvision-net:
    external: true 