version: '3.8'

services:
  ozon-api:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/marketvision}/ozon-api:latest
    container_name: ozon-api-container
    ports:
      - "3002:3002"  # gRPC
      - "3005:3005"  # HTTP health check
    environment:
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G 