version: '3.8'

services:
  ozon-api:
    build: .
    container_name: marketvision-ozon-parser
    ports:
      - "3002:3002"  # gRPC
      - "3005:3005"  # HTTP health check
    environment:
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
      - OZON_API_TOKEN=${OZON_API_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    shm_size: '2gb'
    networks:
      - marketvision-net

networks:
  marketvision-net:
    external: true
