version: '3.8'

services:
  wb-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketvision-wb-parser
    ports:
      - "3000:3000"  # gRPC (для прямого доступа, если нужно)
      - "3003:3003"    # HTTP health check
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - marketvision-net

networks:
  marketvision-net:
    external: true
