version: '3.8'

services:
  nginx-dev:
    image: nginx:alpine
    container_name: marketvision-nginx-dev
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "8080:8080"  # Internal HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ../monorepo-root/tls:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      marketvision-net:
        aliases:
          - marketvision-nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  marketvision-net:
    external: true
