services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: marketvision-postgres
    environment:
      POSTGRES_DB: marketvision
      POSTGRES_USER: marketvision
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketvision"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 