services:
  db-api:
    build: .
    container_name: marketvision-database-api
    ports:
      - "3004:3004"
      - "50051:50051"
    environment:
      - DATABASE_URL=postgresql://marketvision:${POSTGRES_PASSWORD:-password}@postgres:5432/marketvision
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - marketvision-net

networks:
  marketvision-net:
    external: true
