name: 🐳 Docker Build & Deploy

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'monorepo-root/**'
      - 'docker-compose*.yml'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ozon-api, db-api, product-filter-service, wb-api, marketvision-api]
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🔐 Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🏗️ Build and push ${{ matrix.service }}
      uses: docker/build-push-action@v5
      with:
        context: ./monorepo-root/${{ matrix.service }}
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:latest
          ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:${{ github.sha }}
        cache-from: |
          type=gha
          type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:buildcache
        cache-to: |
          type=gha,mode=max
          type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:buildcache,mode=max

    - name: 📊 Cache Statistics
      run: |
        echo "🔍 Статистика кэша для ${{ matrix.service }}:"
        echo "⏱️ Время сборки: $(date -u +%H:%M:%S)"
        echo "📦 Использование кэша:"
        docker system df --format 'table {{.Type}}\t{{.TotalCount}}\t{{.Size}}' | head -10

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🚀 Deploy to server
      run: |
        echo "🚀 Deploying updated containers..."
